// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKgMqAQOPuIzqkzNu9z7Pja_tMR1soxY',
    appId: '1:603460368117:android:4786bed3d65d904c63b7bc',
    messagingSenderId: '603460368117',
    projectId: 'singinflutter-4dba9',
    storageBucket: 'singinflutter-4dba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNHoJsuFbgAFU7AswikgKlS2W-JZTsNI',
    appId: '1:603460368117:ios:ee7879ee7502cc4d63b7bc',
    messagingSenderId: '603460368117',
    projectId: 'singinflutter-4dba9',
    storageBucket: 'singinflutter-4dba9.appspot.com',
    androidClientId: '603460368117-vn7uka125cj5eddg28150ns18vdjfm1h.apps.googleusercontent.com',
    iosClientId: '603460368117-62vnss7vlu6c7dkt5h4mb5hrnhbsf7gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.newwareFinalProject',
  );
}
